### ISSUE TITLE
Update liccheck to 0.6.4

### ISSUE THREAD

**Issue by amdemas** [andersy005/gh-action-py-liccheck#9]
Is it possible to update the version of liccheck installed to the latest?

**Comment by andersy005** [comment]
It might be simpler to expose the liccheck version as part of the action's user-provided inputs

https://github.com/andersy005/gh-action-py-liccheck/blob/81380e3834ee9ec3101c412bc37683b858dc51d8/src/main.ts#L54

This way users will have more control over which version to use. I'll look into this in the coming days.
